name: Go Build, Test, and Coverage

on:
  push:
    branches: [main]
  pull_request:

    
branches: [main]

jobs:

  
build:

    
runs-on:
 
ubuntu-latest


    
steps:

      
-
 
uses:
 
actions/checkout@v3


      
-
 
name:
 
Setup
 
Go

        
uses:
 
actions/setup-go@v3

        
with:

          
go-version:
 
'1.18'


      
-
 
name:
 
Install
 
Dependencies

        
run:
 
go
 
mod
 
download


      
-
 
name:
 
Build
        run: go build -v ./

  test:
    runs-on: ubuntu-latest


    
steps:

      
-
 
uses:
 
actions/checkout@v3


      
-
 
name:
 
Setup
 
Go

        
uses:
 
actions/setup-go@v3

        
with:

          
go-version:
 
'1.18'


      
-
 
name:
 
Test

        
run:
 
go
 
test -v ./...

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Get coverage
        run: go test -v -coverprofile=coverage.out ./...

  artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ runner.workspace }}/build
          name: go-build
